version: '3.4'

services:
  theatre.api:
    build:
      context: .
      dockerfile: Src/Theatre.API/Dockerfile
    ports:
    - 8080:80
    depends_on: 
    - theatre.redis
  theatre.redis:
    image: redis:alpine
    container_name: redis
    ports:
    - 6379:6379

